import Head from "next/head";
import { gql, useQuery, NetworkStatus } from "@apollo/client";

const getStoriesQuery = gql`
  query getStories {
    getStories {
      isSuccess
      message
      result {
        id
        title
        content
        creator
        interestedUsers
      }
    }
  }
`;

export default function StoriesContainer() {
  const { data } = useQuery(getStoriesQuery, {
    notifyOnNetworkStatusChange: true,
  });
  console.log(data.getStories.result);
  return (
    <div>
      <Head>
        <title>Stories</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Hello</main>
    </div>
  );
}
