import { GetStaticProps } from "next";
import Head from "next/head";
import { fetchStoriesAxios } from "./../../axios/axios";

export const getStaticProps: GetStaticProps = async () => {
  const { getStories } = (await fetchStoriesAxios()).data.data;
  const { isSuccess, message, result } = getStories;
  return {
    props: {
      isSuccess,
      message,
      storiesData: result,
    },
  };
};

export default function StoriesContainer({
  storiesData,
}: {
  storiesData: {
    id: string;
    title: string;
    content: string;
    creator: string;
  }[];
}) {
  return (
    <div>
      <Head>
        <title>Stories</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {storiesData.map((story, key) => (
          <div key={key}>{story.title}</div>
        ))}
      </main>
    </div>
  );
}
