import Head from "next/head";
import { ChangeEvent, useEffect, useState } from "react";
import { signUpUserAxios } from "../../axios/axios";

interface ICredentialsInput {
  email: string;
  password: string;
  name?: string;
  avatar?: string;
}

export default function Home() {
  const [isSignIn, setIsSignIn] = useState<boolean>(false);
  const [userCredentials, setUserCredentials] = useState<ICredentialsInput>({
    email: "",
    password: "",
    avatar: "",
    name: "",
  });

  const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
    event.preventDefault();
    setUserCredentials({
      ...userCredentials,
      [event.target.name]: event.target.value,
    });
  };

  const handleSubmit = async () => {
    if (isSignIn) {
      console.log("Sign in");
    } else {
      const { signUpUser } = (await signUpUserAxios(userCredentials)).data.data;
      const { isSuccess, message, result } = signUpUser;
      console.log(result);
    }
    console.log(userCredentials);
  };
  return (
    <div>
      <Head>
        <title>Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <button onClick={() => setIsSignIn(!isSignIn)}>Toggle Auth</button>
        <br />
        {!isSignIn && (
          <>
            <label>Name</label>
            <input
              value={userCredentials.name}
              name="name"
              type="text"
              onChange={(event) => handleChange(event)}
              placeholder="Input your name here..."
            />
            <br />
            <label>Avatar</label>
            <input
              value={userCredentials.avatar}
              name="avatar"
              type="text"
              onChange={(event) => handleChange(event)}
              placeholder="Upload your avatar here..."
            />
            <br />
          </>
        )}
        <label>Email</label>
        <input
          value={userCredentials.email}
          name="email"
          type="email"
          onChange={(event) => handleChange(event)}
          placeholder="Input your email here..."
        />
        <br />
        <label>Password</label>
        <input
          value={userCredentials.password}
          name="password"
          type="password"
          onChange={(event) => handleChange(event)}
          placeholder="Input your password here..."
        />
        <br />
        <button onClick={handleSubmit}>Submit!</button>
      </main>
    </div>
  );
}
